
insert into COUNTRY(COUNTRY_CODE,NAME)VALUES('ZA','South Africa');
insert into COUNTRY(COUNTRY_CODE,NAME)VALUES('MZ', 'Mozambique');
insert into COUNTRY(COUNTRY_CODE,NAME )VALUES('NA', 'Namibie');

insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('EC','ZA', 'Eastern Cape');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('WC','ZA', 'Western Cape');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME )VALUES('GP','ZA', 'Gauteng');

insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('MA','MZ', 'Maputo');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('NA','MZ', 'Nampula');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME )VALUES('IN','MZ', 'Inhambane');

insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('CA','NA', 'Caprivi');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME)VALUES('ER','NA', 'Erongo');
insert into PROVINCE(PROVINCE_CODE,COUNTRY_CODE,NAME )VALUES('HA','NA', 'Hardap');